// Precompile the gNVC JSON Schema into a standalone validator so the app ships no Ajv runtime
// (and needs no eval under a strict CSP). Output is committed; re-run after editing the schema.
import { readFileSync, writeFileSync } from 'node:fs';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';

const schema = JSON.parse(readFileSync(new URL('../spec/gnvc-card.schema.json', import.meta.url), 'utf8'));
const ajv = new Ajv2020({ code: { source: true, esm: true }, allErrors: true, strict: true, strictRequired: false });
const validate = ajv.compile(schema);
let code = standaloneCode(ajv, validate);
// Inline Ajv's one runtime helper so the output has no imports at all.
code = code.replace(
  'require("ajv/dist/runtime/ucs2length").default',
  '(s => { let l = 0; for (const _ of s) l++; return l; })'
);
if (/require\(|^import /m.test(code)) throw new Error('validator still has a runtime import');
code = '// Generated by scripts/compile-schema.mjs from spec/gnvc-card.schema.json. Do not edit.\n' + code;
writeFileSync(new URL('../src/lib/core/gnvc-validate.js', import.meta.url), code);
console.log('wrote src/lib/core/gnvc-validate.js (' + code.length + ' bytes)');
